#!/usr/bin/env node
// build.js — Generates serviceAccount.js from Vercel environment variables.
// Run automatically by Vercel before serving (see vercel.json buildCommand).
//
// Required env vars in Vercel project settings:
//   SA_CLIENT_EMAIL   — service account email from the JSON key file
//   SA_PRIVATE_KEY    — full private key string (Vercel preserves \n in env vars)
//   SA_FOLDER_ID      — Google Drive folder ID (optional)

const fs = require('fs');
const path = require('path');

const email     = process.env.SA_CLIENT_EMAIL  || '';
const key       = process.env.SA_PRIVATE_KEY   || '';
const folderId  = process.env.SA_FOLDER_ID     || '';

if (!email || !key) {
  console.warn('[build.js] WARNING: SA_CLIENT_EMAIL or SA_PRIVATE_KEY not set.');
  console.warn('           The app will load but Google Sheets features will not work.');
  console.warn('           Add these environment variables in your Vercel project settings.');
}

const content = `// Auto-generated by build.js from Vercel environment variables.
// Do not edit manually.
const PRIVATE_KEY = ${JSON.stringify(key)};
const PRIVATE_KEY_PARTS = [PRIVATE_KEY];
const SERVICE_ACCOUNT_EMAIL = ${JSON.stringify(email)};
const FOLDER_ID = ${JSON.stringify(folderId)};
`;

const outPath = path.join(__dirname, 'serviceAccount.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[build.js] serviceAccount.js written.');
console.log(`[build.js]   email  : ${email ? email : '(not set)'}`);
console.log(`[build.js]   key    : ${key ? key.substring(0, 40) + '…' : '(not set)'}`);
console.log(`[build.js]   folder : ${folderId || '(not set)'}`);
